from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

class DatabaseConnectionRequest(BaseModel):
    """Schema for database connection request."""
    connection_string: str = Field(..., description="Database connection string (e.g., postgresql://user:pass@host/db)")

class DatabaseConnectionResponse(BaseModel):
    """Schema for database connection response."""
    success: bool = Field(..., description="Whether the connection was successful")
    connection_id: str = Field(..., description="Unique ID for the established connection")
    database_type: str = Field(..., description="Type of the connected database (e.g., postgresql, sqlite)")
    message: str = Field(..., description="Status message")

class NaturalLanguageQueryRequest(BaseModel):
    """Schema for natural language query request."""
    connection_id: str = Field(..., description="ID of the active database connection")
    natural_language_query: str = Field(..., description="The natural language question to ask the database")
    model: Optional[str] = Field(None, description="Optional model hint (database chat uses Groq Llama)")

class QueryExecutionResponse(BaseModel):
    """Schema for query execution response."""
    success: bool = Field(..., description="Whether the query execution was successful")
    generated_sql: Optional[str] = Field(None, description="The SQL query generated by the LLM")
    results: Optional[List[Dict[str, Any]]] = Field(None, description="The results of the query execution")
    row_count: Optional[int] = Field(None, description="Number of rows returned")
    error: Optional[str] = Field(None, description="Error message if execution failed")

class SchemaResponse(BaseModel):
    """Schema for database schema retrieval."""
    success: bool = Field(..., description="Whether the schema retrieval was successful")
    database_type: str = Field(..., description="Type of the database")
    database_schema: Optional[Dict[str, Any]] = Field(None, description="Raw dictionary representation of the schema")
    formatted_schema: Optional[str] = Field(None, description="Human-readable schema representation provided to the LLM")
    error: Optional[str] = Field(None, description="Error message if retrieval failed")

class DisconnectResponse(BaseModel):
    """Schema for database disconnection response."""
    success: bool = Field(..., description="Whether the disconnection was successful")
    message: str = Field(..., description="Status message")
